apiVersion: v1
kind: Namespace
metadata:
  name: dsa-solver
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dsa-solver-config
  namespace: dsa-solver
data:
  MODEL_NAME: "gemini-2.5-flash"
  APP_TITLE: "DSA Solver"
  LANGSMITH_TRACING: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: dsa-solver-secrets
  namespace: dsa-solver
type: Opaque
data:
  # These will be base64 encoded values from GitHub secrets
  GOOGLE_API_KEY: "" # Will be injected by GitHub Actions
  LANGSMITH_API_KEY: "" # Will be injected by GitHub Actions
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsa-solver
  namespace: dsa-solver
  labels:
    app: dsa-solver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dsa-solver
  template:
    metadata:
      labels:
        app: dsa-solver
    spec:
      containers:
      - name: dsa-solver
        image: IMAGE_TAG  # This will be replaced by GitHub Actions
        ports:
        - containerPort: 8501
          protocol: TCP
        env:
        - name: MODEL_NAME
          valueFrom:
            configMapKeyRef:
              name: dsa-solver-config
              key: MODEL_NAME
        - name: APP_TITLE
          valueFrom:
            configMapKeyRef:
              name: dsa-solver-config
              key: APP_TITLE
        - name: LANGSMITH_TRACING
          valueFrom:
            configMapKeyRef:
              name: dsa-solver-config
              key: LANGSMITH_TRACING
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: dsa-solver-secrets
              key: GOOGLE_API_KEY
        - name: LANGSMITH_API_KEY
          valueFrom:
            secretKeyRef:
              name: dsa-solver-secrets
              key: LANGSMITH_API_KEY
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: dsa-solver-service
  namespace: dsa-solver
  labels:
    app: dsa-solver
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8501
    protocol: TCP
  selector:
    app: dsa-solver